In [2]:
import numpy as np
import pandas as pd

In [6]:
## Loading the data
df = pd.read_csv(r"anime.csv")

In [7]:
df.head()

   Rank                                              Title  Score
0     1  Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...   9.10
1     2  Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...   9.07
2     3  Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...   9.06
3     4  Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...   9.06
4     5  Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...   9.05

### Make a new column for episode count

In [ ]:

df.loc[1]['Title']

## as we can see there are episode counts in the title

'Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473,707 members'

In [ ]:
def extract_episode(txt):
    check = False
    data = ""
    for i in txt:
        if i == ')':
            break

        if check == True:
            data += i

        if i == '(':
            check = True
            
    return data

In [ ]:
df["Episodes"] = df['Title'].apply(extract_episode)

In [20]:
df['Episodes'] = df['Episodes'].str.replace(" eps","")

In [24]:
df['Episodes'] = df['Episodes'].astype(int)
df.head()

   Rank                                              Title  Score  Episodes
0     1  Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...   9.10        64
1     2  Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...   9.07        24
2     3  Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...   9.06        13
3     4  Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...   9.06        51
4     5  Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...   9.05        10

### Make a new column for time stamp

In [25]:
df.loc[0]['Title']

'Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr 2009 - Jul 20103,218,472 membersManga StoreVolume 1€4.58Preview'

In [29]:
def extraction_time(txt):
    check = False
    data = ""
    for i in range(len(txt)):
        if txt[i]==')':
            for j in range(i+1,i+20):
                data += txt[j]

    return data

In [32]:
df['Total_time'] = df['Title'].apply(extraction_time)

df.head()

,Rank,Title,Score,Episodes,Total_time
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.10,64,Apr 2009 - Jul 2010
1,2,"Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...",9.07,24,Apr 2011 - Sep 2011
2,3,Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...,9.06,13,Oct 2022 - Dec 2022
3,4,"Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...",9.06,51,Apr 2015 - Mar 2016
4,5,Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...,9.05,10,Apr 2019 - Jul 2019

In [34]:
## Adding total months 
def calculate_total_months(duration):
    """
    Calculate the total number of months from a string like:
    'Apr 2009 - Jul 2010'
    """
    start_str, end_str = duration.split(" - ")

    start = pd.to_datetime(start_str, format="%b %Y")
    end = pd.to_datetime(end_str, format="%b %Y")

    total_months = (
        (end.year - start.year) * 12 +
        (end.month - start.month) + 1
    )

    return total_months

In [36]:
df['Months'] = df['Total_time'].apply(calculate_total_months)
df.head()

,Rank,Title,Score,Episodes,Total_time,Months
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.10,64,Apr 2009 - Jul 2010,16
1,2,"Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...",9.07,24,Apr 2011 - Sep 2011,6
2,3,Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...,9.06,13,Oct 2022 - Dec 2022,3
3,4,"Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...",9.06,51,Apr 2015 - Mar 2016,12
4,5,Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...,9.05,10,Apr 2019 - Jul 2019,4

### which anime has the highest score

In [38]:
df[df['Score'] == df['Score'].max()] ['Title']

0    Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...
Name: Title, dtype: str

### give me top 5 highest scoring anime

In [44]:
# df['Score'].nlargest(5)
top_5_titles = df.nlargest(5, "Score")["Title"]
top_5_titles

0    Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...
1    Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...
2    Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...
3    Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...
4    Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...
Name: Title, dtype: str

### which anime has the highest episode count

In [52]:
df[df['Episodes'] == df['Episodes'].max()]

,Rank,Title,Score,Episodes,Total_time,Months
15,16,"GintamaTV (201 eps)Apr 2006 - Mar 20101,034,41...",8.94,201,Apr 2006 - Mar 2010,48

### Animes with top5 episode count

In [57]:
top_5_epi_count = df.nlargest(5,'Episodes')
top_5_epi_count

,Rank,Title,Score,Episodes,Total_time,Months
15,16,"GintamaTV (201 eps)Apr 2006 - Mar 20101,034,41...",8.94,201,Apr 2006 - Mar 2010,48
7,8,Hunter x Hunter TV (148 eps)Oct 2011 - Sep 201...,9.04,148,Oct 2011 - Sep 2014,36
11,12,Ginga Eiyuu DensetsuOVA (110 eps)Jan 1988 - Ma...,9.02,110,Jan 1988 - Mar 1997,111
42,43,Hajime no IppoTV (75 eps)Oct 2000 - Mar 200255...,8.76,75,Oct 2000 - Mar 2002,18
24,25,"MonsterTV (74 eps)Apr 2004 - Sep 20051,041,081...",8.87,74,Apr 2004 - Sep 2005,18

### which is the longest running anime

In [59]:
df[df['Months']==df['Months'].max()]

,Rank,Title,Score,Episodes,Total_time,Months
11,12,Ginga Eiyuu DensetsuOVA (110 eps)Jan 1988 - Ma...,9.02,110,Jan 1988 - Mar 1997,111